name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet
      run: nuget restore Source
      working-directory: ./Source

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build with MSBuild
      run: msbuild /p:Configuration=Release
      working-directory: ./Source